image: node:18.18.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/


build:
  stage: build
  script:
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*

pages:
  stage: deploy
  script:
      - ls
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*

prod:deploy:
  stage: deploy
  when: manual
  only:
    - main
  image: docker:latest
  tags:
    - deploy
  variables:
    GIT_STRATEGY: none
  environment:
    name: production
    url: https://www.offerwallmonetization.com